const LinkedList = require('./linkedList1')
const DoublyLinkedList = require('./linkedList2')

// let list = new LinkedList()

// list.append(15)
// list.append(10)
// list.insert(0, 1)
// list.insert(2, 2)
// list.print()
// console.log(list.isEmpty())
// console.log(list.size())
// console.log(list.indexOf(1))
// list.remove(1)
// list.print()
// console.log(list.getHead())
// list.remove(2)
// list.print()

let list = new DoublyLinkedList()

list.insert(0, 1)
list.insert(1, 2)
list.insert(2, 3)
list.insert(3, 4)
list.insert(4, 5)
list.print()
list.removeAt(0)
list.print()
list.removeAt(1)
list.print()
